#!/bin/bash

WIDTH=160
HEIGHT=120
T=20
XDIM=3
NOISE=0.2
FEM_REDUCE=0.8
NPROC=3
FEM_TYPE=0
TYPE=0

FILENAME_DATA=data/moviedot_data.bin
FILENAME_SOLUTION=results/moviedot_prolongated_datavector.bin
FILENAME_OUT=results/movie_dot.jpg
FILENAME_OUT_MOVIE=results/movie_dot.mp4
DIRNAME_OUT="results/movie_dot/"

# remove old data
rm -f $FILENAME_DATA $FILENAME_SOLUTION $FILENAME_OUT_MOVIE results/moviedot_reduced_datavector.bin

# generate problem
#./test_movie_generate_dot --test_width=$WIDTH --test_height=$HEIGHT --test_T=$T --test_filename_data=$FILENAME_DATA --test_filename_solution=$FILENAME_SOLUTION --test_filename_gamma0=data/moviedot_gamma0.bin --test_noise=$NOISE --test_generate_data=true --test_generate_gamma0=false --test_type=$TYPE --test_xdim=$XDIM
./test_movie_generate_3dot --test_width=$WIDTH --test_height=$HEIGHT --test_T=$T --test_filename_data=$FILENAME_DATA --test_filename_solution=$FILENAME_SOLUTION --test_filename_gamma0=data/moviedot_gamma0.bin --test_noise=$NOISE --test_generate_data=true --test_generate_gamma0=false --test_type=$TYPE --test_xdim=$XDIM

# define parameters
PARAM_FILENAME="--test_filename_in=$FILENAME_DATA --test_filename_out=moviedot --test_width=$WIDTH --test_height=$HEIGHT --test_xdim=$XDIM --test_T=$T --test_type=$TYPE"
PARAM_BASIC="--test_printinfo=true --test_graph_save=true"
PARAM_LOG="--log_or_not=true --log_or_not_func_call=true --log_or_not_file_line=true --log_or_not_level=true"

PARAM_FEM="--test_fem_reduce=$FEM_REDUCE --test_fem_type=$FEM_TYPE"

## additional PETSc parameters
PARAM_PETSC="--petsc_options=\"\""

## concrenate all parameters
PARAM_ALL="$PARAM_FILENAME $PARAM_BASIC $PARAM_FEM $PARAM_LOG $PARAM_PETSC"

## run the job
mpiexec -n $NPROC ./test_petscvector_fem_movie $PARAM_ALL
#./test_petscvector_fem_movie $PARAM_ALL

# show results
if [ -f data/moviedot_data.bin ]
then
	./gui_show_movie --filename=$FILENAME_DATA --width=$WIDTH --T=$T --xdim=$XDIM --title="Original movie" --type=$TYPE &
fi

REDUCED_WIDTH=80
if [ -f results/moviedot_reduced_datavector.bin ]
then
	./gui_show_movie --filename=results/moviedot_reduced_datavector.bin --width=$REDUCED_WIDTH --T=$T --xdim=$XDIM --title="Reduced FEM_REDUCE=$FEM_REDUCE FEM_TYPE=$FEM_TYPE" --type=$TYPE &
fi

if [ -f results/moviedot_prolongated_datavector.bin ]
then
	./gui_show_movie --filename=$FILENAME_SOLUTION --width=$WIDTH --T=$T --xdim=$XDIM --title="Prolongated FEM_REDUCE=$FEM_REDUCE FEM_TYPE=$FEM_TYPE" --type=$TYPE &
fi


# create movie
./util_dlib_vec_to_image --filename_in=$FILENAME_DATA --filename_in2=$FILENAME_SOLUTION --filename_out=$FILENAME_OUT --width=$WIDTH --T=$T --xdim=$XDIM --type=$TYPE

#mencoder mf://./results/movie_dot/*.jpg -mf w=800:h=600:fps=25:type=jpg -ovc copy -oac copy -o results/output.avi
ffmpeg -framerate 2 -i $DIRNAME_OUT%02d.jpg -c:v libx264 -r 30 -pix_fmt yuv420p $FILENAME_OUT_MOVIE


