function plot_brain( brain_vertices, brain_faces, brain_data )

% Render brain
patch('Faces', brain_faces,...
      'Vertices', brain_vertices, ...
      'FaceVertexCData', brain_data,...
      'EdgeColor',       'none',        ...
      'FaceLighting',    'gouraud',     ...
      'AmbientStrength', 0.15, ...
      'FaceColor', 'interp', ...
      'CDataMapping', 'scaled');

end

