#!/bin/bash
#

echo "------------ We are ready to download submodules from GitHub! ------------";

git submodule update --init --recursive
git submodule update --recursive --remote

echo "------------ Modules downloaded! ------------";

