#!/bin/bash   

T=1000
REPEAT=1
K=3
NOISE=0.1
NPROC=3
FEM_REDUCE=0.05
FEM_TYPE=0

# remove old files
rm -f data/test_image/signal1D_solution.bin data/test_image/signal1D_data.bin results/lugano_recovered.bin results/lugano_gamma.bin

# generate signal
./test_signal1D_generate --test_Tperiod=$T --test_repeat_nmb=$REPEAT --test_filename_data=data/signal1D_data.bin --test_filename_solution=data/signal1D_solution.bin --test_filename_gamma0=data/signal1D_gamma.bin --test_K=$K --test_noise=$NOISE --test_generate_data=true --test_generate_gamma0=true

# solve problem
PARAM_FILENAME="--test_filename_in=data/signal1D_data.bin --test_filename_solution=data/signal1D_solution.bin --test_filename_gamma0=data/signal1D_gamma.bin --test_filename_out=signal1D"
PARAM_BASIC="--test_K=$K --test_annealing=1"
#PARAM_THETA="--test_Theta=1.0 --test_Theta=2.0 --test_Theta=3.0"
PARAM_EPSSQR="--test_epssqr=1e-2 --test_epssqr=1e-1 --test_epssqr=1e0 --test_epssqr=1e1 --test_epssqr=1e2 --test_epssqr=1e3"
PARAM_PREPROCESS="--test_cutdata=false --test_scaledata=false"
PARAM_TSSOLVER="--tssolver_maxit=1 --tssolver_debugmode=0"
PARAM_SHORTINFO="--test_shortinfo=false"
PARAM_LOG="--log_or_not=false"

PARAM_QPSOLVER="--graphh1femmodel_gammasolvertype=1 --spgqpsolver_maxit=1000 --spgqpsolver_debugmode=0 --spgqpsolver_stop_difff=false --spgqpsolver_stop_normgp=true --spgqpsolver_eps=1e-6"

PARAM_FEM="--test_fem_reduce=$FEM_REDUCE --test_fem_type=$FEM_TYPE"

## additional PETSc parameters
PARAM_PETSC="--petsc_options=\"\""

## concrenate all parameters
PARAM_ALL="$PARAM_FILENAME $PARAM_BASIC $PARAM_EPSSQR $PARAM_PREPROCESS $PARAM_TSSOLVER $PARAM_SHORTINFO $PARAM_LOG $PARAM_QPSOLVER $PARAM_PETSC $PARAM_THETA $PARAM_FEM" 

## run the job
#./test_signal1D $PARAM_ALL
mpiexec -n $NPROC ./test_signal $PARAM_ALL
#/home/lukas/soft/petsc_old/arch-linux2-c-debug/bin/mpiexec -n 2 ./test_signal1D $PARAM_ALL

# gui show vectors
if [ -f data/signal1D_data.bin ]
then
    ./gui_show_vec --filename=data/signal1D_data.bin --title="signal data" & 
fi

if [ -f results/signal1D_gamma.bin ]
then
	./gui_show_gamma --filename=results/signal1D_gamma.bin --K=$K  --title="gamma solution" &
fi

if [ -f results/signal1D_recovered.bin ]
then
	./gui_show_vec --filename=results/signal1D_recovered.bin --title="recovered signal" &
fi

