#!/bin/bash   

T=1000
REPEAT=1
K=3
NOISE=0.5
NPROC=1
FEM_REDUCE=0.5
FEM_TYPE=0
FUZZIFIER=1.2
XDIM=1
ANNEALING=10

NAME=signal1D
FILENAME_DATA=data/signal1D_data.bin
FILENAME_DATA_SOLUTION=data/signal1D_solution.bin
FILENAME_GAMMA0=data/signal1D_gamma0.bin
FILENAME_GAMMA=results/signal1D_gamma.bin
FILENAME_SOLUTION=results/signal1D_recovered.bin

# remove old files
rm -f $FILENAME_SOLUTION $FILENAME_DATA $FILENAME_DATA_SOLUTION $FILENAME_GAMMA $FILENAME_GAMMA0

# generate signal
./test_signal1D_generate --test_Tperiod=$T --test_repeat_nmb=$REPEAT --test_filename_data=$FILENAME_DATA --test_filename_solution=$FILENAME_DATA_SOLUTION --test_filename_gamma0=$FILENAME_GAMMA0 --test_K=$K --test_noise=$NOISE --test_generate_data=true --test_generate_gamma0=true

# solve problem
PARAM_FILENAME="--test_fuzzifier=$FUZZIFIER --test_filename_in=$FILENAME_DATA --test_filename_solution=$FILENAME_DATA_SOLUTION --test_filename_gamma0=$FILENAME_GAMMA0 --test_filename_out=$NAME"
PARAM_BASIC="--test_xdim=$XDIM --test_K=$K --test_annealing=$ANNEALING --test_printstats=false --test_printinfo=true"
#PARAM_THETA="--test_Theta=1.0 --test_Theta=2.0 --test_Theta=3.0 --tssolver_thetasolver_updatebeforesolve=false"
PARAM_PREPROCESS="--test_cutdata=false --test_scaledata=false"
PARAM_TSSOLVER="--tssolver_maxit=100 --tssolver_debugmode=0 --tssolver_debug_print_annealing=true"
PARAM_SHORTINFO="--test_shortinfo=false"
PARAM_LOG="--log_or_not=true --log_or_not_func_call=true --log_or_not_file_line=true --log_or_not_level=true"

#PARAM_KMEANSFUZZYSOLVER="--graphh1femmodel_gammasolvertype=1 --spgqpsolver_maxit=1000 --spgqpsolver_debugmode=0 --spgqpsolver_stop_difff=false --spgqpsolver_stop_normgp=true --spgqpsolver_eps=1e-6"

PARAM_FEM="--test_fem_reduce=$FEM_REDUCE --test_fem_type=$FEM_TYPE"

## additional PETSc parameters
PARAM_PETSC="--petsc_options=\"\""

## concrenate all parameters
PARAM_ALL="$PARAM_FILENAME $PARAM_BASIC $PARAM_PREPROCESS $PARAM_TSSOLVER $PARAM_SHORTINFO $PARAM_LOG PARAM_KMEANSFUZZYSOLVER $PARAM_PETSC $PARAM_THETA $PARAM_FEM" 

## run the job
./test_signal_fuzzykmeans $PARAM_ALL
#mpiexec -n $NPROC ./test_signal_fuzzykmeans $PARAM_ALL
#/home/lukas/soft/petsc_old/arch-linux2-c-debug/bin/mpiexec -n $NPROC ./test_signal_fuzzykmeans $PARAM_ALL

# gui show vectors
if [ -f $FILENAME_DATA ]
then
    ./gui_show_vec --filename=$FILENAME_DATA --title="signal data" & 
fi

if [ -f $FILENAME_GAMMA ]
then
	./gui_show_gamma --filename=$FILENAME_GAMMA --K=$K  --title="gamma solution" --type=1 &
fi

if [ -f $FILENAME_SOLUTION ]
then
	./gui_show_vec --filename=$FILENAME_SOLUTION --title="recovered signal" &
fi

