#!/bin/bash   

K=3

PARAM_FILENAME="--test_signal_in=data/mysample.bin --test_signal_solution=data/mysample_solution.bin --test_signal_gamma0=data/mysample_gamma0_K3.bin --test_signal_out=mysample"
PARAM_BASIC="--test_K=$K --test_Theta=1.0 --test_Theta=2.0 --test_Theta=3.0 --test_annealing=1"
PARAM_EPSSQR="--test_epssqr=1e-2 --test_epssqr=1e-1 --test_epssqr=1e0 --test_epssqr=1e1 --test_epssqr=1e2 --test_epssqr=1e3"
PARAM_PREPROCESS="--test_cutdata=false --test_scaledata=false"
PARAM_TSSOLVER="--tssolver_maxit=1 --tssolver_debugmode=0"
PARAM_SHORTINFO="--test_shortinfo=false"
PARAM_LOG="--log_or_not=false"

PARAM_QPSOLVER="--graphh1femmodel_gammasolvertype=1 --spgqpsolver_maxit=10000 --spgqpsolver_debugmode=0 --spgqpsolver_stop_difff=false --spgqpsolver_stop_normgp=true --spgqpsolver_eps=1e-8"

## additional PETSc parameters
PARAM_PETSC="--petsc_options=\"\""

## concrenate all parameters
PARAM_ALL="$PARAM_FILENAME $PARAM_BASIC $PARAM_EPSSQR $PARAM_PREPROCESS $PARAM_TSSOLVER $PARAM_SHORTINFO $PARAM_LOG $PARAM_QPSOLVER $PARAM_PETSC"

## run the job
#./test_signal1D $PARAM_ALL
mpiexec -n 2 ./test_signal $PARAM_ALL
#/home/lukas/soft/petsc_old/arch-linux2-c-debug/bin/mpiexec -n 2 ./test_signal1D $PARAM_ALL

./gui_show_gamma --filename=results/mysample_gamma.bin --K=$K &
