#!/bin/bash   

WIDTH=120
HEIGHT=80
T=40
K=2
NOISE=0.01
TYPE=2

./test_movie_generate_3dot --test_width=$WIDTH --test_height=$HEIGHT --test_type=$TYPE --test_T=$T --test_filename_data=data/movie3dot_data.bin --test_filename_solution=data/movie3dot_solution.bin --test_filename_gamma0=data/movie3dot_gamma0.bin --test_K=$K --test_noise=$NOISE --test_generate_data=true --test_generate_gamma0=true

./gui_show_movie --filename=data/movie3dot_data.bin --type=$TYPE --width=$WIDTH --T=$T --xdim=3 --title="movie data" &
./gui_show_movie --filename=data/movie3dot_solution.bin --type=$TYPE --width=$WIDTH --T=$T --xdim=3 --title="movie solution" &
./gui_show_movie --filename=data/movie3dot_gamma0.bin --type=$TYPE --width=$WIDTH --T=$T --xdim=3 --title="movie gamma0" &
