#!/bin/bash   

MYTESTWIDTH=4
MYTESTHEIGHT=3
XDIM=1
ANNEALING=1
K=2
FEM_REDUCE=-1
NPROC=4

# remove old files
rm results/seq_image_recovered.bin results/seq_image_gamma.bin

# define parameters
PARAM_FILENAME="--test_filename_in=data/test_image/seq_image.bin --test_filename_solution=data/test_image/seq_image.bin --test_filename_out=seq_image --test_width=$MYTESTWIDTH --test_height=$MYTESTHEIGHT --test_xdim=$XDIM"
PARAM_BASIC="--test_K=$K --test_annealing=$ANNEALING --test_printstats=false --test_printinfo=true"
PARAM_GAMMA="--test_filename_gamma0=data/test_image/seq_image_gamma.bin"
#PARAM_THETA="--test_Theta=0.8 --test_Theta=0.2"
#PARAM_THETA="--test_Theta=0.25 --test_Theta=0.5 --test_Theta=0.75"
PARAM_THETA=""
PARAM_EPSSQR="--test_epssqr=1e0"
#PARAM_EPSSQR="--test_epssqr=1e-6 --test_epssqr=1e-5 --test_epssqr=1e-4 --test_epssqr=1e-3 --test_epssqr=1e-2 --test_epssqr=1e-1 --test_epssqr=1e0 --test_epssqr=1e1 --test_epssqr=1e2 --test_epssqr=1e3"
#PARAM_EPSSQR="--test_epssqr=1e-4 --test_epssqr=1e-2 --test_epssqr=1e0 --test_epssqr=1e2"
PARAM_PREPROCESS="--test_cutdata=false --test_scaledata=false"
PARAM_TSSOLVER="--tssolver_maxit=0 --tssolver_eps=1e-5 --tssolver_debugmode=0"
PARAM_SHORTINFO="--test_shortinfo=true --test_shortinfo_filename=shortinfo/seq.txt --tssolver_debug_print_gamma_solution=false"
PARAM_LOG="--log_or_not=true --log_or_not_func_call=true --log_or_not_file_line=true --log_or_not_level=true"

PARAM_SOLVER="--spgqpsolver_maxit=1000 --spgqpsolver_debugmode=0 --spgqpsolver_stop_difff=false --spgqpsolver_stop_normgp=true --spgqpsolver_eps=1e-6"
PARAM_SOLVER_PRINT="--spgqpsolver_debug_print_it=false --tssolver_debug_print_gamma=false --tssolver_debug_print_theta=false --tssolver_debug_print_it=false"

PARAM_FEM="--test_fem_reduce=$FEM_REDUCE --test_fem_type=4"

## additional PETSc parameters
PARAM_PETSC="--petsc_options=\"\""

## concrenate all parameters
PARAM_ALL="$PARAM_FILENAME $PARAM_BASIC $PARAM_GAMMA $PARAM_THETA $PARAM_FEM $PARAM_EPSSQR $PARAM_PREPROCESS $PARAM_TSSOLVER $PARAM_SHORTINFO $PARAM_LOG $PARAM_SOLVER $PARAM_SOLVER_PRINT $PARAM_PETSC"

## run the job
#./test_signal1D $PARAM_ALL
/home/lukas/soft/petsc_old/arch-linux2-c-debug/bin/mpiexec -n $NPROC ./test_image $PARAM_ALL
#mpiexec -n $NPROC ./test_image $PARAM_ALL
#./test_image $PARAM_ALL

# show results
./gui_show_image --filename=data/test_image/seq_image.bin --xdim=$XDIM --width=$MYTESTWIDTH --title="Data image" &

if [ -f results/seq_image_recovered.bin ]
then
    ./gui_show_image --filename=results/seq_image_recovered.bin --xdim=$XDIM --width=$MYTESTWIDTH --title="Recovered image" &
fi
if [ -f results/seq_image_gamma.bin ]
then
    ./gui_show_image --filename=results/seq_image_gamma.bin --xdim=1 --width=$MYTESTWIDTH --title="Gamma" &
fi

