#!/bin/bash   

MYTESTSIZE=100
XDIM=3
NOISE=0.0
ANNEALING=1
K=3
FEM_REDUCE=-1
NPROC=4

rm -f data/test_image/illia_avatar_color_solution.bin data/test_image/illia_avatar_color_data.bin results/illia_avatar_color_recovered.bin results/illia_avatar_color_gamma.bin

# generate example
./util_dlib_image_to_vec --filename_in=data/test_image/illia_avatar.jpg --filename_out=data/test_image/illia_avatar_color_solution.bin --noise=0.0 --new_width=$MYTESTSIZE --xdim=$XDIM
./util_dlib_image_to_vec --filename_in=data/test_image/illia_avatar.jpg --filename_out=data/test_image/illia_avatar_color_data.bin --noise=$NOISE --new_width=$MYTESTSIZE --xdim=$XDIM

# define parameters
PARAM_FILENAME="--test_filename_in=data/test_image/illia_avatar_color_data.bin --test_filename_solution=data/test_image/illia_avatar_color_solution.bin --test_filename_out=illia_avatar_color --test_width=$MYTESTSIZE --test_height=$MYTESTSIZE --test_xdim=$XDIM"
PARAM_BASIC="--test_K=$K --test_annealing=$ANNEALING --test_printstats=false --test_printinfo=true"
#PARAM_THETA="--test_Theta=0.0 --test_Theta=0.2 --test_Theta=0.4 --test_Theta=0.6 --test_Theta=0.8 --test_Theta=1.0"
#PARAM_THETA="--test_Theta=0.25 --test_Theta=0.5 --test_Theta=0.75"
PARAM_EPSSQR="--test_epssqr=1e-6 --test_epssqr=1e-5 --test_epssqr=1e-4 --test_epssqr=1e-3 --test_epssqr=1e-2 --test_epssqr=1e-1 --test_epssqr=1e0 --test_epssqr=1e1 --test_epssqr=1e2 --test_epssqr=1e3"
#PARAM_EPSSQR="--test_epssqr=1e-4 --test_epssqr=1e-2 --test_epssqr=1e0 --test_epssqr=1e2"
PARAM_PREPROCESS="--test_cutdata=false --test_scaledata=false"
PARAM_TSSOLVER="--tssolver_maxit=100 --tssolver_eps=1e-5 --tssolver_debugmode=0"
PARAM_SHORTINFO="--test_shortinfo=true --test_shortinfo_filename=shortinfo/illia_avatar.txt --tssolver_debug_print_gamma_solution=false"
PARAM_LOG="--log_or_not=true --log_or_not_func_call=true --log_or_not_file_line=true --log_or_not_level=true"

PARAM_SOLVER="--spgqpsolver_maxit=1000 --spgqpsolver_debugmode=0 --spgqpsolver_stop_difff=false --spgqpsolver_stop_normgp=true --spgqpsolver_eps=1e-6"
PARAM_SOLVER_PRINT="--spgqpsolver_debug_print_it=false --tssolver_debug_print_gamma=false --tssolver_debug_print_theta=false --tssolver_debug_print_it=false"

PARAM_FEM="--test_fem_reduce=$FEM_REDUCE --test_fem_type=2"

## additional PETSc parameters
PARAM_PETSC="--petsc_options=\"\""

## concrenate all parameters
PARAM_ALL="$PARAM_FILENAME $PARAM_BASIC $PARAM_THETA $PARAM_FEM $PARAM_EPSSQR $PARAM_PREPROCESS $PARAM_TSSOLVER $PARAM_SHORTINFO $PARAM_LOG $PARAM_SOLVER $PARAM_SOLVER_PRINT $PARAM_PETSC"

## run the job
#./test_signal1D $PARAM_ALL
#/home/lukas/soft/petsc_old/arch-linux2-c-debug/bin/mpiexec -n $NPROC ./test_image $PARAM_ALL
mpiexec -n $NPROC ./test_image $PARAM_ALL
#./test_image $PARAM_ALL

# show results
if [ -f data/test_image/illia_avatar_color_data.bin ]
then
	./gui_show_image --filename=data/test_image/illia_avatar_color_data.bin --xdim=$XDIM --width=$MYTESTSIZE --title="Data image" &
fi

if [ -f results/illia_avatar_color_recovered.bin ]
then
	./gui_show_image --filename=results/illia_avatar_color_recovered.bin --xdim=$XDIM --width=$MYTESTSIZE --title="Recovered image" &
fi

if [ -f results/illia_avatar_color_gamma.bin ]
then
	./gui_show_image --filename=results/illia_avatar_color_gamma.bin --xdim=1 --width=$MYTESTSIZE --title="Gamma" &
fi

