#!/bin/bash   

MYTESTSIZE=50
XDIM=1
NOISE=0.1
ANNEALING=1
K=5
FEM_REDUCE=1

# generate example
./util_dlib_image_to_vec --in_filename=data/test_image/illia_avatar.jpg --out_filename=data/test_image/illia_avatar_color_solution.bin --noise=0.0 --new_width=$MYTESTSIZE --xdim=$XDIM
./util_dlib_image_to_vec --in_filename=data/test_image/illia_avatar.jpg --out_filename=data/test_image/illia_avatar_color_data.bin --noise=$NOISE --new_width=$MYTESTSIZE --xdim=$XDIM

# define parameters
PARAM_FILENAME="--test_image_in=data/test_image/illia_avatar_color_data.bin --test_image_solution=data/test_image/illia_avatar_color_solution.bin --test_image_out=illia_avatar_color --test_width=$MYTESTSIZE --test_height=$MYTESTSIZE --test_xdim=$XDIM"
PARAM_BASIC="--test_K=$K --test_annealing=$ANNEALING --test_printstats=false --test_printinfo=true"
#PARAM_THETA="--test_Theta=0.0 --test_Theta=0.25 --test_Theta=0.5 --test_Theta=0.75 --test_Theta=1.0"
PARAM_FEM="--test_fem_reduce=$FEM_REDUCE --test_fem_type=3"
#PARAM_FEM=""
#PARAM_EPSSQR="--test_epssqr=1e-6 --test_epssqr=1e-5 --test_epssqr=1e-4 --test_epssqr=1e-3 --test_epssqr=1e-2 --test_epssqr=1e-1 --test_epssqr=1e0 --test_epssqr=1e1 --test_epssqr=1e2"
PARAM_EPSSQR="--test_epssqr=1e-4 --test_epssqr=1e-2 --test_epssqr=1e0 --test_epssqr=1e2"
PARAM_PREPROCESS="--test_cutdata=false --test_scaledata=false"
PARAM_TSSOLVER="--tssolver_maxit=100 --tssolver_eps=1e-6 --tssolver_debugmode=0"
PARAM_SHORTINFO="--test_shortinfo=false --tssolver_debug_print_gamma_solution=false"
PARAM_LOG="--log_or_not=true --log_or_not_func_call=true --log_or_not_file_line=true --log_or_not_level=true"

PARAM_SOLVER="--spgqpsolver_maxit=1000 --spgqpsolver_debugmode=0 --spgqpsolver_stop_difff=false --spgqpsolver_stop_normgp=true --spgqpsolver_eps=1e-8"
PARAM_SOLVER_PRINT="--spgqpsolver_debug_print_it=false --tssolver_debug_print_gamma=false --tssolver_debug_print_theta=false --tssolver_debug_print_it=false"

## additional PETSc parameters
PARAM_PETSC="--petsc_options=\"\""

## concrenate all parameters
PARAM_ALL="$PARAM_FILENAME $PARAM_BASIC $PARAM_THETA $PARAM_FEM $PARAM_EPSSQR $PARAM_PREPROCESS $PARAM_TSSOLVER $PARAM_SHORTINFO $PARAM_LOG $PARAM_SOLVER $PARAM_SOLVER_PRINT $PARAM_PETSC"

## run the job
#./test_signal1D $PARAM_ALL
#mpiexec -n 2 ./test_signal1D $PARAM_ALL
/home/lukas/soft/petsc_old/arch-linux2-c-debug/bin/mpiexec -n 1 ./test_image $PARAM_ALL

# show results
#./gui_show_image --filename=data/test_image/illia_avatar_color_data.bin --xdim=$XDIM --width=$MYTESTSIZE --title="Data image" &
./gui_show_image --filename=results/illia_avatar_color_recovered.bin --xdim=$XDIM --width=$MYTESTSIZE --title="Recovered image" &
./gui_show_image --filename=results/illia_avatar_color_gamma.bin --xdim=1 --width=$MYTESTSIZE --title="Gamma" &
