#!/bin/bash

KM=6
K=2
ANNEALING=2
T=3000
XDIM=2

NAME=xt_1lag
FILENAME_CSV=data/test_entropy/xt_1lag.csv
FILENAME_DATA=data/test_entropy/xt_1lag_data.bin
FILENAME_GAMMA=results/xt_1lag_gamma.bin
DATA_TYPE=2

# from csv to bin
./util_csv_to_vec --filename_in=$FILENAME_CSV --filename_out=$FILENAME_DATA --T=$T --xdim=$XDIM --print=false --permute=false

PARAM_BASIC="--test_K=$K --test_Km=$KM --test_filename_in=$FILENAME_DATA --test_filename_out=$NAME --test_annealing=$ANNEALING --test_scaledata=false --test_data_type=$DATA_TYPE --test_xdim=$XDIM"
#PARAM_GAMMA0="--test_filename_gamma0=data/y_K3_gamma0.bin"
PARAM_EPSSQR="--test_epssqr=1e-1"
#PARAM_EPSSQR="--test_epssqr=1e-1 --test_epssqr=1e1 --test_epssqr=1e2 --test_epssqr=1e3 --test_epssqr=1e4 --test_epssqr=1e5"
PARAM_PRINT="--test_printstats=true --test_printinfo=true"
PARAM_THETA="" #--test_Theta
PARAM_SHORTINFO="--test_shortinfo=true" # --test_shortinfo_header --test_shortinfo_values --test_shortinfo_filename
PARAM_LOG="--log_or_not=true --log_or_not_func_call=true --log_or_not_file_line=true --log_or_not_level=true"

PARAM_TSSOLVER="--tssolver_maxit=100"
PARAM_TSSOLVER_PRINT="--tssolver_debug_print_it=true --tssolver_debug_print_annealing=true --tssolver_debug_print_theta=true"
 
PARAM_QPSOLVER="--spgqpsolver_maxit=1000 --spgqpsolver_eps=1e-6 --spgqpsolver_stop_difff=false --spgqpsolver_stop_normgp=true"
PARAM_QPSOLVER_PRINT="--spgqpsolver_debug_print_it=false" 

PARAM_ENTROPYSOLVER1="--entropyh1femmodel_thetasolvertype=0"
PARAM_ENTROPYSOLVER2="--entropysolverdlib_maxit=10  --entropysolverdlib_eps=1e-4 --entropysolverdlib_integration_eps=1e-8"
PARAM_ENTROPYSOLVER_PRINT="--entropysolverdlib_debug_print_moments=false --entropysolverdlib_debug_print_it=true --entropysolverdlib_debug_print_content=false --entropysolverdlib_debug_print_integration=false"
PARAM_ENTROPYSOLVER_INTEGRATION="--entropysolverdlib_integration_type=3 --entropysolverdlib_integration_mineval=0 --entropysolverdlib_integration_maxeval=100000 --entropysolverdlib_integration_nstart=10000 --entropysolverdlib_integration_nincrease=10000"

#PARAM_ENTROPYSOLVER1="--entropyh1femmodel_thetasolvertype=2"
#PARAM_ENTROPYSOLVER2="--entropysolvernewton_maxit=20 --entropysolvernewton_eps=1e-6 --entropysolvernewton_integration_eps=1e-8 --entropysolvernewton_newton_coeff=0.9 --entropysolvernewton_integrationtype=1"
#PARAM_ENTROPYSOLVER_PRINT="--entropysolvernewton_debug_print_it=true --entropysolvernewton_debug_print_Axb=false"

PARAM_ALL="$PARAM_BASIC $PARAM_GAMMA0 $PARAM_EPSSQR $PARAM_PRINT $PARAM_THETA $PARAM_SHORTINFO $PARAM_LOG $PARAM_TSSOLVER $PARAM_TSSOLVER_PRINT $PARAM_QPSOLVER $PARAM_QPSOLVER_PRINT $PARAM_ENTROPYSOLVER1 $PARAM_ENTROPYSOLVER2 $PARAM_ENTROPYSOLVER_PRINT $PARAM_ENTROPYSOLVER_INTEGRATION"

./test_entropy $PARAM_ALL

if [ -f $FILENAME_GAMMA ]
then
	./gui_show_gamma --filename=$FILENAME_GAMMA --K=$K --title="Gamma" &
fi
